#!/bin/bash

# This function need the file(s) "/sys/class/backlight/*/brightness"
# to have permition 666.

if [ "$#" -ne 1 ]; then
  echo "brightness need to have the new brightness level has argument (0-100)" >&2
  exit -1
fi
if ! [[ "$1" =~ ^[0-9]+$ ]]; then
  echo "First argument need to be integer (0-100)" >&2
  exit -1
fi
if [ $1 -gt 100 ]; then
  echo "brightness cannot be greater than 100" >&2
  exit -1
fi
if [ $1 -lt 1 ]; then
  echo "brightness cannot be lower than 1" >&2
  exit -1
fi

max_br=$(cat /sys/class/backlight/*/max_brightness)
r=$(echo "$1/100" | bc -l)
br=$(echo "$r*$max_br / 1" | bc)
sudo echo "$br" > /sys/class/backlight/*/brightness

